### ISSUE TITLE
Bumping cross package versions

### ISSUE THREAD

**Issue by sergeybekrin** [Updater/semantic-release-monorepo#29]
Hey, thanks for such handy extension! I've noticed that release doesn't bump cross-dependent packages in monorepo. Do you think it's possible to achieve with root-level hook in any way? Thanks.

**Comment by pmowrer** [comment]
Hi there! I'm guessing the feature you describe is something similar to what `lerna publish` does ([possibly relevant discussion)](https://github.com/semantic-release/semantic-release/issues/193#issuecomment-364340261)? 

If my assumption is correct, I'm afraid this feature request is out-of-scope. This project is just a thin wrapper on top of `semantic-release`, augmenting its behavior to work in a monorepo (hopefully to be deprecated by `semantic-release` itself eventually). It was never intended to introduce features outside of what `semantic-release` does.
