### ISSUE TITLE
How to `semantic-release-cli setup` for a monorepo

### ISSUE THREAD

**Issue by nemoDreamer** [Updater/semantic-release-monorepo#30]
Hi there, thanks for this package!
We've got a multi-package repo that we wish to publish using `semantic-release` on Jenkins, but even on my local machine, I can't seem to get past GitHub Enterprise / Artifactory NPM authentication hurdles (https://github.com/semantic-release/cli/issues/115) which I feel are getting compounded by me also trying to get `~-monorepo` to work.

What are the steps to follow to use `semantic-release-cli setup` together with `semantic-release-monorepo`?

Or alternatively, what key/value pairs in which `package.json` files coupled with what `env` variables or cli flags need to be present?

**Comment by gr2m** [comment]
Hey @nemoDreamer see an extended discussion on monorepos & semantic-release at https://github.com/semantic-release/semantic-release/issues/193#issuecomment-364310081, please read that. Note that `semantic-release-monorepo` is not our project, we can’t help with that at all.

In short, the maintainers of semantic-release don’t have use mono repos so it won’t be us who add support for it. If someone comes up with a good design and takes on ownership, we’d be happy to add them to the team :)

**Comment by gr2m** [comment]
oops sorry mixed up my browser tabs :) meant to respond to your issue on semantic-release, sorry for the noise 👋

**Comment by pmowrer** [comment]
Hi there @nemoDreamer! Sorry, didn't see this until now. I'd be happy to help you out getting setup. The hope is that the README should cover the setup. Is the problem you're running into getting Github access configured?

**Comment by adrianschmidt** [comment]
I'm having what I believe is the same or a similar problem, where running `npx semantic-release` uses the `$GH_USER` and `$GH_TOKEN` environment variables, but running `npx lerna exec --concurrency 1 -- npx --no-install semantic-release` prompts me for my GitHub username and password.

I'm thinking it's Lerna's `exec` command that somehow blocks the environment variables, but I'm not sure.

Does anyone have any ideas on what could be wrong, and how to resolve this?
