### ISSUE TITLE
Override `tagFormat`?

### ISSUE THREAD

**Issue by FezVrasta** [Updater/semantic-release-monorepo#33]
The doc says there's a way to override the `tagFormat` but it doesn't seem to have any effect.

I tried to put `tagFormat: "@${version}"` (to obtain `package-name@x.x.x` instead of `package-name-vx.x.x`) but it seems to be ignored.

The only reference in the code is here:
https://github.com/Updater/semantic-release-monorepo/blob/e08eeaf3054d6d9a7730b883589312afd7d4459c/src/index.js#L37

And it doesn't seem to address any way to customize it?

**Comment by FezVrasta** [comment]
As workaround I found out I can use this command:

```
"semantic-release": "lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo --tag-format='${LERNA_PACKAGE_NAME}@\\${version}'"
```

I'm not sure if this was the intended way to use the `tag-format` option tho.

**Comment by pmowrer** [comment]
Excellent solution!

You're right in that `tagFormat` isn't well documented. Just haven't gotten around to it. This library hardcodes the value as you observed, but options passed on the command-line will override those in a plugin config. 

If you don't mind, please add this solution to the tiny `tagFormat` section of the README.

**Comment by FezVrasta** [comment]
Done #35
