### ISSUE TITLE
semantic-release-monorepo is broken because of semantic-release-plugin-decorators@v1.2.2

### ISSUE THREAD

**Issue by constantology** [Updater/semantic-release-monorepo#40]
Hello,

First off, I've copied and pasted this from the issue I created for [semantic-release-plugin-decorators](/Updater/semantic-release-plugin-decorators/issues/5), so apologies for describing your own module to you. 😅

We use `lerna`, `semantic-release` and `semantic-release-monorepo` to version and publish our projects' shared modules.

The change that triggered `semantic-release-plugin-decorators@v1.2.2` has broken our pipeline. 

This is because in order to use `semantic-release-monorepo` you need to put your `analyzeCommits` and `generateNotes` configurations inside a `monorepo` Object of your `release` configuration. 
See the [semantic-release-monorepo: Example of use with non-default set of plugins](/Updater/semantic-release-monorepo#example-of-use-with-non-default-set-of-plugins) for an example of this.

If we include an `release.analyzeCommits` configuration, then `semantic-release-monorepo` does not execute at all. If we put it inside a `monorepo` Object, as outlined above, then it is now ignored because of the change in `semantic-release-plugin-decorators@v1.2.2` and as such, neither out `preset: eslint`, nor our custom `releaseRules: Object` get picked up by `semantic-release-monorepo`, which then prevents `semantic-release` from versioning and publishing, as it can't find any valid changes.

Since you're the owner of both modules, I'm unsure about where you want to make the fix, however, it would be great if you could fix it, I don't know if other people are experiencing the same issue or not, but it may only be a matter of time.

For now, we've hard versioned `semantic-release-plugin-decorators` to `v1.2.1`, at the same time, it would be nice to not be locked into this version to be able to receive future updates. 🙂

Thanks,
Christos.

**Comment by pmowrer** [comment]
Hi @constantology! Sorry to hear about the trouble.

> If we include an release.analyzeCommits configuration, then semantic-release-monorepo does not execute at all

What's the output then? Please run with `--debug` flag for more details.

**Comment by pmowrer** [comment]
Fixed in https://github.com/Updater/semantic-release-plugin-decorators/issues/5
