### ISSUE TITLE
Lerna exec not executing properly in conjunction with semantic-release-monorepo

### ISSUE THREAD

**Issue by BasKiers** [Updater/semantic-release-monorepo#48]
Setting up a monorepo environment we found that lerna does not execute the semantic-release command, provided in the README of this package, correctly. `--concurrency 1` does not work and lerna spawns 4 processes at once and the flags for semantic-release-monorepo like --tag-format do not work. 

Looking in to it it seems that the `--` option of lerna is deprecated and should be omitted. When ommitting `--` the concurrency seems to work and the `--tag-format` option also works as expected.

The command that was not working was:
```
yarn lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo -d --debug
```
We got it working by changing it to this:
```
yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo -d --debug"
```

**Comment by BasKiers** [comment]
This behaviour seems to be caused by `yarn`. The above command does work when using `npx`.

**Comment by pmowrer** [comment]
I believe `yarn` deprecated the `--` syntax after 1.0.0. Perhaps we should add a `yarn`-specific example to the README
