### ISSUE TITLE
Fixed versioning

### ISSUE THREAD

**Issue by jimthedev** [Updater/semantic-release-monorepo#50]
If using lerna and wanting fixed mode versioning is there a way to get this to respect that?

**Comment by pmowrer** [comment]
I'm afraid not. Fixed versioning doesn't really fit into the `semantic-release-monorepo` workflow; it is designed to run against each individual package. 

That said, it shouldn't be too difficult to achieve something like that. You might use regular `semantic-release` and replace its `publish` plugin with one that runs `lerna`'s publish using the release version that `semantic-release` calculates.

**Comment by jimthedev** [comment]
Cool thanks. I ended up getting my project working with independent versioning for now. The key was that my CI (Drone) wasn't putting the repo path into the PATH and as such my npmrc with my custom auth wasn't being picked up.
