### ISSUE TITLE
generateNotes step failing

### ISSUE THREAD

**Issue by ecozoic** [Updater/semantic-release-monorepo#52]
We've been using semantic-release-monorepo for a couple months using a lerna project. Been working great until recently this error pops up during `generateNotes` step:

```
[2:46:29 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "[Function: ]"
[2:46:29 PM] [semantic-release] › ✖  Failed step "generateNotes" of plugin "[Function: ]"
[2:46:29 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/node_modules/import-from/node_modules/resolve-from/index.js:11:9)
    at module.exports (/node_modules/import-from/node_modules/resolve-from/index.js:34:41)
    at module.exports (/node_modules/import-from/index.js:4:49)
    at requirePlugin (/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/node_modules/semantic-release/lib/plugins/normalize.js:34:28)
    at pReduce (/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
```

Seems to be some sort of issue with `semantic-release-plugin-decorators`, which uses `import-from` to load a plugin, and it's getting passed an object (I actually think its an array) instead of a string for `moduleId` which throws.

If I stop extending from semantic-release-monorepo, semantic-release runs fine (but obviously generates bad release notes, etc that aren't filtered by packages).  Any ideas?

We did recently move repo to yarn, not sure if that could cause weirdness.  (Update - tested w/ NPM and still seeing same issue....)

Also some info:
Tested both semantic-release versions `15.6` and `15.9`
Node version `10.8.0` (also tested `10.6.0`)

Here's some additional output showing difference between what gets passed for the `analyzeCommits` step vs. the `generateNotes` step: I'm logging the passed `moduleId` to the console. For analyzeCommits, we have a string, but for generateNotes we have an array containing a string
```
[3:17:03 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: ]"
@semantic-release/commit-analyzer
[3:17:04 PM] [semantic-release] [[Function: ]] › ℹ  Found 6 commits for package since last release
[3:17:04 PM] [semantic-release] [[Function: ]] › ℹ  Analysis of 6 commits complete: minor release
[3:17:04 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: ]"
[3:17:04 PM] [semantic-release] › ℹ  The next release version is 1.1.0
[3:17:04 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "[Function: ]"
[ '@semantic-release/release-notes-generator' ]
```

As a super quick fix, I edited `requirePlugin` in semantic-release-plugin-decorators/index to this:
```
const requirePlugin = module => {
  console.log(module);

  if (Array.isArray(module)) {
    return importFrom(process.cwd(), module[0]);
  }

  return importFrom(process.cwd(), module);
};
```

This solves the issue. I am not sure what could have caused this regression? Also not sure if this is an issue with how the monorepo is using the decorator (`wrapPlugin`) or in the decorator itself.

**Comment by ecozoic** [comment]
This actually looks like its an issue with @semantic-release/release-notes-generator@7.0.0, not semantic-release-monorepo really.

**Comment by ecozoic** [comment]
Technically this package won't work for semantic-releease versions starting at `15.8.x` because that's when @semantic-release/release-notes-generator dependency was bumped to 7.0.0. Might need to indicate that somewhere or try to figure out what's causing the crash.

**Comment by pmowrer** [comment]
Thanks for the report @ecozoic! I'll look into bridging this gap!

**Comment by jimthedev** [comment]
@ecozoic did you find or open an issue with release-notes-generator on this so they know that this resulted in a break?

**Comment by hassankhan** [comment]
It seems the issue is with the decorator package's usage of `import-from`, as per the issue @jimthedev created on the `semantic-release` tracker.

**Comment by pmowrer** [comment]
@ecozoic Sorry for the delay, finally had some time to dig into this! 

I'm actually not able to reproduce this using `semantic-release` 15.9.12, `release-notes-generator` 7.0.1 and `semantic-release-monorepo` 6.0.3. That said, given it has to do with a plugin interface, I imagine it might have something to do with a particular configuration of plugins. Would you mind sharing what plugin config you're running with when this error occurs? To easily capture it, run with the `--debug` flag and it will spit out the plugin configuration at the beginning of the run.

**Comment by stalniy** [comment]
@pmowrer my config:

```js
const PACKAGE_NAME = process.env.LERNA_PACKAGE_NAME || process.env.npm_package_name

module.exports = {
  tagFormat: `${PACKAGE_NAME}@\${version}`,
  verifyConditions: [
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/github'
  ],
  prepare: [
    {
      path: '@semantic-release/changelog',
      changelogTitle: '# Change Log\n\nAll notable changes to this project will be documented in this file.'
    },
    '@semantic-release/npm',
    {
      path: '@semantic-release/git',
      message: `chore(release): ${PACKAGE_NAME}@\${nextRelease.version} [skip ci]`
    }
  ],
  success: []
}
```

I run this command:
```
semantic-release -e semantic-release-monorepo -e ../../tools/semantic-release --no-ci
```

**Comment by stalniy** [comment]
just a note that when I rolled back to 

```
    "@semantic-release/changelog": "^2.0.0",
    "@semantic-release/git": "^6.0.0",
    "semantic-release": "15.6.3"
```

Everything works good again (with "semantic-release-monorepo": "^6.0.1")

**Comment by pmowrer** [comment]
Thanks @stalniy! Unfortunately, nothing sticks out as a likely culprit. Do you mind also posting the output of running with the `--debug` flag. This is what I'm referring to:

```bash
[12:04:46 AM] [semantic-release] › ℹ  Running semantic-release version 15.9.12
  semantic-release:config options values: { branch: 'upgrade-semantic-release',
  semantic-release:config   repositoryUrl: 'git@github.com:Updater/angular-common.git',
  semantic-release:config   tagFormat: '@updater/ui-alert-v${version}',
  semantic-release:config   analyzeCommits: [AsyncFunction],
  semantic-release:config   generateNotes: [AsyncFunction],
  semantic-release:config   verifyConditions: [],
  semantic-release:config   monorepo:
  semantic-release:config    { analyzeCommits: { format: 'atom' },
  semantic-release:config      generateNotes: '@semantic-release/release-notes-generator' },
  semantic-release:config   success: [],
  semantic-release:config   fail: [],
  semantic-release:config   _: [],
  semantic-release:config   e:
  semantic-release:config    [ 'semantic-release-monorepo',
  semantic-release:config      '/Users/pmowrer/Code/Updater/angular-common/.releaserc-publish.js' ],
  semantic-release:config   'dry-run': true,
  semantic-release:config   d: true,
  semantic-release:config   dryRun: true,
  semantic-release:config   b: 'upgrade-semantic-release',
  semantic-release:config   ci: false,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': '../../node_modules/.bin/semantic-release',
  semantic-release:config   noCi: true } +0ms
```
---
The change in `semantic-release` 15.8 doesn't seem to be breaking for plugins -- the plugin function signature looks the same, but there are a couple of new properties on the context object (`cwd` and `env`). All of those plugin updates seem to mainly be about using `semantic-releases` definition of `cwd` over `process.cwd`. 

There [is a place in `semantic-release-plugin-decorators`](https://github.com/Updater/semantic-release-plugin-decorators/blob/master/src/index.js#L4) were we could make that same change, but based on the errors that have been reported, it doesn't seem like this is the problem. For whatever reason, it appears `generateNotes` is passed an unexpected plugin configuration (a multi-dimensional array?). I am able to reproduce the error using the following (illegal) config:

```
{
  ...
  "monorepo": {
    "generateNotes": [["@semantic-release/release-notes-generator"]],
  }
}
```

**Comment by stalniy** [comment]
Hm... thanks for looking into this!

Somewhere in release notes I saw that now it's possible to pass multiple `generateNotes` functions

**Comment by pmowrer** [comment]
> Somewhere in release notes I saw that now it's possible to pass multiple generateNotes functions

This should be supported and I believe it works. For example, this seems to work:

```
{
  ...
  monorepo: {
    "generateNotes": ["@semantic-release/release-notes-generator", "@semantic-release/release-notes-generator"],
  }
}
```

**Comment by pmowrer** [comment]
I am able to reproduce it in a [different plugin project](https://travis-ci.org/Updater/semantic-release-github-pr/builds/424412553?utm_source=github_status&utm_medium=notification). I would expect to see the same problem with `semantic-release-monorepo` then and I'm confused why I'm not seeing it. 

Anyway, hopefully solving it for the other plugin solves it for all. Pretty sure the reason we're seeing these errors is due to `generateNotes` being converted to a "multi plugin" and its default being updated from a single plugin to an array of a single plugin:

https://github.com/semantic-release/semantic-release/commit/59899894529a707eee1c1bf777e130b50c20806a#diff-205c5cf625514dcf92e20a30d112c1cd

**Comment by pmowrer** [comment]
After digging through this some more, I have a much better understanding of why the error is happening. It has entirely to do with the aforementioned `generateNotes` plugin interface change that took place in `semantic-release` in 15.7.0. This interface is already supported, but requires a different but already existing wrapper from the `semantic-release-plugin-decorators` library.

Initially, I thought fixing it would require a breaking change, as plugin configurations using the "mono" plugin syntax (and not an array) may be incompatible, but I tested it out and it seems to work just fine. I suppose that backwards compatibility is what kept it from being a breaking change in `semantic-release` to being with. The fix is available in [`6.1.0`](https://github.com/Updater/semantic-release-monorepo/releases/tag/v6.1.0). 

Thanks everyone for the help!

**Comment by grrowl** [comment]
I'm seeing this on node 10 with the following versions:

```
  "semantic-release": "^15.12.4",
  "semantic-release-monorepo": "^6.1.1"
```

Failed task output:

```
> root@ release /app
--
  | > lerna exec --stream --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
  |  
  | lerna notice cli v3.10.2
  | lerna info versioning independent
  | lerna info ci enabled
  | lerna info Executing command in 2 packages: "npx --no-install semantic-release -e semantic-release-monorepo"
  | @activepipe/bench-renderer: [12:58:44 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.2
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ✔  Run automated release from branch master
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ✔  Allowed to push to the Git repository
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ℹ  No git tag version found
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ℹ  No previous release found, retrieving all commits
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ℹ  Found 478 commits since last release
  | @activepipe/bench-renderer: [12:58:45 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: ]"
  | @activepipe/bench-renderer: [12:58:46 AM] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "[Function: ]"
  | @activepipe/bench-renderer: [12:58:46 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Expected `moduleId` to be of type `string`, got `object`
  | @activepipe/bench-renderer:     at resolveFrom (/app/node_modules/resolve-from/index.js:11:9)
  | @activepipe/bench-renderer:     at module.exports (/app/node_modules/resolve-from/index.js:34:41)
  | @activepipe/bench-renderer:     at module.exports (/app/node_modules/import-from/index.js:4:49)
  | @activepipe/bench-renderer:     at requirePlugin (/app/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
  | @activepipe/bench-renderer:     at resolvePluginFn (/app/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
  | @activepipe/bench-renderer:     at /app/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
  | @activepipe/bench-renderer:     at validator (/app/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
  | @activepipe/bench-renderer:     at pReduce (/app/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
  | @activepipe/bench-renderer:     at Promise.all.then.value (/app/node_modules/p-reduce/index.js:16:10)
  | @activepipe/bench-renderer:     at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
  | @activepipe/bench-renderer: { TypeError: Expected `moduleId` to be of type `string`, got `object`
  | @activepipe/bench-renderer:     at resolveFrom (/app/node_modules/resolve-from/index.js:11:9)
  | @activepipe/bench-renderer:     at module.exports (/app/node_modules/resolve-from/index.js:34:41)
  | @activepipe/bench-renderer:     at module.exports (/app/node_modules/import-from/index.js:4:49)
  | @activepipe/bench-renderer:     at requirePlugin (/app/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
  | @activepipe/bench-renderer:     at resolvePluginFn (/app/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
  | @activepipe/bench-renderer:     at /app/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
  | @activepipe/bench-renderer:     at validator (/app/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
  | @activepipe/bench-renderer:     at pReduce (/app/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
  | @activepipe/bench-renderer:     at Promise.all.then.value (/app/node_modules/p-reduce/index.js:16:10)
  | @activepipe/bench-renderer:     at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
```

here is my `release.config.js`:

```
module.exports = {
  "extends": "@internal/release-config",
  plugins: [
    "@semantic-release/git",
    {
      assets: ['packages/**/package.json', 'packages/**/package-lock.json']
    }
  ]
}
```

and here is `@internal/release-config/index.js`:

```
module.exports = {
  // https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit by default
  analyzeCommits: ['@semantic-release/commit-analyzer'],
  generateNotes: ['@semantic-release/release-notes-generator'],

  verifyConditions: [
    '@semantic-release/npm',
    '@semantic-release/github',
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'package-lock.json'],
    },
  ],

  prepare: [
    '@semantic-release/npm',
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'package-lock.json'],
    },
  ],
  publish: ['@semantic-release/npm', '@semantic-release/github'],
  success: ['@semantic-release/github'],
  fail: ['@semantic-release/github'],
}
```

**Comment by grrowl** [comment]
I see this might be related to this open issue https://github.com/Updater/semantic-release-monorepo/issues/65#issuecomment-434774294
