### ISSUE TITLE
lerna semantic-release-monorepo babel

### ISSUE THREAD

**Issue by lifeiscontent** [Updater/semantic-release-monorepo#63]
Hey there, thanks for the awesome project.

I was wondering if there's a way to kick off a build to `@babel/cli` when semantic-release-monorepo figures out which packages to publish.

**Comment by pmowrer** [comment]
Hello! 😎 

> when semantic-release-monorepo figures out which packages to publish

It really depends on your use case. You could create a `semantic-release` `publish` plugin. You could use the `prepublishOnly` hook (as mentioned in the other issue). This package just modifies `semantic-release`'s default behavior somewhat.
