### ISSUE TITLE
how to link packages which are semantically released?

### ISSUE THREAD

**Issue by lifeiscontent** [Updater/semantic-release-monorepo#64]
@pmowrer how do you link packages that depend on other packages within the repo? I'm using something like this:

```
  "dependencies": {
    "@airpage/icons": "^0.0.0-semantically-released"
  }
```

but the issue is when I use the package, npm gracefully falls back says it can't find the version `0.0.0-semantically-released` and then asks me to pick a version.

when using `lerna publish` the package.json will be modified to reflect the new version so it is handled, but since we're not using `lerna publish` to publish the package anymore, that hook is no longer an option.

**Comment by pmowrer** [comment]
Hi @lifeiscontent!

> how do you link packages that depend on other packages within the repo

`yarn link` (or `npm link`). Is this the kind of linking you are referring to?

**Comment by lifeiscontent** [comment]
@pmowrer no I’m specifically talking about dependencies within a package. The way lerna does local dependency linking (so it doesn’t hit npm or the yarn registry) is by specifying the version of the package.json within a lerna package you depend on.

**Comment by lifeiscontent** [comment]
@pmowrer I can put together an example if you want

**Comment by lifeiscontent** [comment]
```
root/
  package.json
  packages/
    a/
      package.json
    b/
      package.json
```

a: package.json

```json
{
  "name": "a",
  "main": "lib/index.js",
  "version": "0.0.0-semantically-released"
}
```

b: package.json

```json
{
  "name": "b",
  "main": "lib/index.js",
  "version": "0.0.0-semantically-released",
   "dependencies": {
     "a": "^0.0.0-semantically-released"
   }
}
```

essentially, if I use module `b` in another app when I do `yarn add b` npm/yarn will gracefully fallback and say version "0.0.0-semantically-released" cannot be found for package `a` please choose one.

which is obviously not the desired behavior.

**Comment by pmowrer** [comment]
You have to provide a "real" dependency version number to `yarn`... it can't be `0.0.0-semantically-released`. The `0.0.0-...` version is just a dummy placeholder that `semantic-release` uses, it's not an actual release version of the package. See more in the [`semantic-release` FAQ](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#why-is-the-packagejsons-version-not-updated-in-my-repository).

**Comment by lifeiscontent** [comment]
@pmowrer I understand that, but how would you depend on a package that is not yet released, or a future version of a package?

**Comment by lifeiscontent** [comment]
@pmowrer also with lerna the way the packages get referenced is by the version in the package.json so with lerna if I say `"a": "1.0.5"` it'll actually goto the yarn or npm registry to pull the package which is not the desired behavior.

**Comment by pmowrer** [comment]
> I understand that, but how would you depend on a package that is not yet released, or a future version of a package?

I'm not sure I understand what is meant by that (a workflow example would help), though I'm guessing it's what's been discussed at length in this [`semantic-release` issue](https://github.com/semantic-release/semantic-release/issues/193#issuecomment-364340261). Unfortunately, I don't think this library supports that.

**Comment by lifeiscontent** [comment]
@pmowrer yeah, exactly. the current implementation of packages works, but it obviously doesn't allow for you to use the right versions.

How to do you deal with package dependencies if this isn't something semantic-release-monorepo supports?

**Comment by pmowrer** [comment]
> How to do you deal with package dependencies 

Sorry, that's too vague... what do you mean? What's the scenario?

**Comment by pmowrer** [comment]
> how would I update the other packages to use that new version?

Manually, using `yarn update`, after the package has been published. That's the workflow that is supported. Sorry!

**Comment by jedwards1211** [comment]
@pmowrer so should we use a real version number in the `"version"` field of our `package.json`s, so that other packages in the monorepo can reference that same version number?  I had assumed we have to use `0.0.0-development` with `semantic-release`.
